return {
    --c# 协议转发
    CLIENT_PLAYER_CURRENCY_CHANGED = "CLIENT_PLAYER_CURRENCY_CHANGED", --金币变化
    CLIENT_PLAYER_BINDCURRENCY_CHANGED = "CLIENT_PLAYER_BINDCURRENCY_CHANGED", --绑金变化
    CLIENT_PLAYER_DIAMOND_CHANGED = "CLIENT_PLAYER_DIAMOND_CHANGED", --钻石变化
        
    --lua内部消息
    LUA_ROOM_LEAVE_FISH_ROOM = "LUA_ROOM_LEAVE_FISH_ROOM",

    LUA_ROOM_FISH_CREATE = "LUA_ROOM_FISH_CREATE",
    LUA_ROOM_FISH_DESTROY = "LUA_ROOM_FISH_DESTROY",
    LUA_ROOM_REMOVE_FISH = "LUA_ROOM_REMOVE_FISH",
    LUA_ROOM_FUNCTIONAL_REMOVE_FISH = "LUA_ROOM_FUNCTIONAL_REMOVE_FISH",
    LUA_ROOM_FISH_CREATE_GOLD = "LUA_ROOM_FISH_CREATE_GOLD",

    LUA_ROOM_BULLET_CREATE = "LUA_ROOM_BULLET_CREATE",
    LUA_ROOM_BULLET_DESTROY = "LUA_ROOM_BULLET_DESTROY",
    LUA_ROOM_BULLET_UPDATE_INFO = "LUA_ROOM_BULLET_UPDATE_INFO",
    LUA_ROOM_PENETRATE_CREATE_WEB = "LUA_ROOM_PENETRATE_CREATE_WEB",

    LUA_ROOM_PLAYER_JOIN = "LUA_ROOM_PLAYER_JOIN",
    LUA_ROOM_PLAYER_LEAVE = "LUA_ROOM_PLAYER_LEAVE",
    LUA_ROOM_PLAYER_CURRENCY_CHANGED = "LUA_ROOM_PLAYER_CURRENCY_CHANGED",
    LUA_ROOM_PLAYER_GUNVALUE_CHANGED = "LUA_ROOM_PLAYER_GUNVALUE_CHANGED",
    LUA_ROOM_PLAYER_GUN_CHANGED = "LUA_ROOM_PLAYER_GUN_CHANGED",
    LUA_ROOM_GUN_ROTATION_CHANGED = "LUA_ROOM_GUN_ROTATION_CHANGED",

    LUA_ROOM_LOCK_FIRE_CHANGE = "LUA_ROOM_LOCK_FIRE_CHANGE",
    LUA_ROOM_AUTO_FIRE_CHANGE = "LUA_ROOM_AUTO_FIRE_CHANGE",
    LUA_ROOM_PENETRATE_FIRE_CHANGE = "LUA_ROOM_PENETRATE_FIRE_CHANGE",
    LUA_ROOM_MULTIPLE_FIRE_CHANGE = "LUA_ROOM_MULTIPLE_FIRE_CHANGE",
    LUA_ROOM_CLONE_FIRE_CHANGE = "LUA_ROOM_CLONE_FIRE_CHANGE",
    LUA_ROOM_CLONE_FIRE_OTHER_CHANGE = "LUA_ROOM_CLONE_FIRE_OTHER_CHANGE",

    LUA_ROOM_TRYGET_RELIEF = "LUA_ROOM_TRYGET_RELIEF",

    LUA_ROOM_PLAYER_LASER_ENERGY_CHANGE = "LUA_ROOM_PLAYER_LASER_ENERGY_CHANGE",
    LUA_ROOM_TRY_USE_LASER = "LUA_ROOM_TRY_USE_LASER",
    LUA_ROOM_TRY_USE_LASER_SUCCESS = "LUA_ROOM_TRY_USE_LASER_SUCCESS",
    LUA_ROOM_PLAY_LASER_UI = "LUA_ROOM_PLAY_LASER_UI",
    LUA_ROOM_OTHER_USE_LAYER = "LUA_ROOM_OTHER_USE_LAYER",

    LUA_ROOM_FISHTIDE_NTF = "LUA_ROOM_FISHTIDE_NTF",

    NET_BONUSWHEEL_ACK = "NET_BONUSWHEEL_ACK",
}
